server:
  port:8088

spring:
  datasource:
    url: jdbc:mysql://mi-mysql:3306/microservicios
    username: alvarto
    password: 73200112daniela
    driver: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect